project:
  type: website
  output-dir: docs

website:
  title: "DS"
  favicon: "images/ds.jpg"
  
  page-footer:
    right: |
      <span class="container"><strong>[Contact Dekayz](mailto:derikayz@gmail.com){target="_blank"}</strong></span>
    left: |
      <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
    background: "#004E4F"
    
  navbar:
    
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Projects
        
    right:
      - icon: x
        href: https://twitter.com/dekayz_
        aria-label: Quarto X
        
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme:
      light: [cosmo, theme_light_custom.scss]
      dark: [cosmo, theme_dark_custom.scss]
    css: styles.css
    citations-hover: true
    code-link: true
    code-fold: show
    code-tools: false
    code-block-border-left: "#004E4F"
    

    
editor: visual
  

